### ISSUE TITLE
The bot's summary for a logicalIndian post was incorrect

### ISSUE THREAD

**Issue by r-pushkar** [HunkDivine/samacharbot2#6]
https://www.reddit.com/r/india/comments/4k1mr3/np_without_helmet_driving_and_escaping_in_ranchi/ is the reddit post. The bot summarized text that was not part of the article.

**Comment by r-pushkar** [comment]
@HunkDivine, I would like to start contributing to the repo by solving this issue. I would like some guidance is possible. Thanks.

**Comment by SalmaanP** [comment]
the bot uses [goose](https://github.com/grangier/python-goose) for scraping and getting relevant content from the website. It works most of the time, but on some sites it has issues. So the fix has to be in goose. What we could do is make a different spider or something just for this one website, but it would not be worth it for that much work. So i suggest we can just add the domain to the blacklist [here](https://github.com/HunkDivine/samacharbot2/blob/master/blacklist.py).

**Comment by r-pushkar** [comment]
Ok, I don't know if it has failed for other sources from this site. I'll take a look at that before blacklisting.

**Comment by r-pushkar** [comment]
Do I organize the folder structure of the project(source) as well? Will make it more readable.

**Comment by SalmaanP** [comment]
I added the files which are not used in another folder for now. The rest are used either by the bot or by heroku so i can't mess with them.
